theme = "tokyonight"

[editor]
idle-timeout = 50
true-color = true
mouse = false
shell = ["zsh", "-c"]
completion-replace = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-p = [":run-shell-command tmux split-window -h"]
